Resources:
  yolov8:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: aws-cdk:auto-delete-objects
          Value: "true"
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: YOLOv8SageMakerStack/yolov8-s3/Resource
  yolov8s3Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: yolov8
      PolicyDocument:
        Statement:
          - Action:
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - CustomS3AutoDeleteObjectsCustomResourceProviderRole
                  - Arn
            Resource:
              - Fn::GetAtt:
                  - yolov8
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - yolov8
                        - Arn
                    - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: YOLOv8SageMakerStack/yolov8-s3/Policy/Resource
  yolov8s3AutoDeleteObjectsCustomResource:
    Type: Custom::S3AutoDeleteObjects
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderHandler
          - Arn
      BucketName:
        Ref: yolov8
    DependsOn:
      - yolov8s3Policy
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: YOLOv8SageMakerStack/yolov8-s3/AutoDeleteObjectsCustomResource/Default
  CustomS3AutoDeleteObjectsCustomResourceProviderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: YOLOv8SageMakerStack/Custom::S3AutoDeleteObjectsCustomResourceProvider/Role
  CustomS3AutoDeleteObjectsCustomResourceProviderHandler:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: aws-blogs-artifacts-public
        S3Key: artifacts/ML-13353/CustomS3AutoDeleteObjectsCustomResourceProviderHandler.zip
      Timeout: 900
      MemorySize: 128
      Handler: __entrypoint__.handler
      Role:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderRole
          - Arn
      Runtime: nodejs12.x
      Description:
        Fn::Join:
          - ""
          - - "Lambda function for auto-deleting objects in "
            - Ref: yolov8
            - " S3 bucket."
    DependsOn:
      - CustomS3AutoDeleteObjectsCustomResourceProviderRole
    Metadata:
      aws:cdk:path: YOLOv8SageMakerStack/Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler
      aws:asset:path: asset.CustomS3AutoDeleteObjectsCustomResourceProviderHandler
      aws:asset:property: Code
  yolov8notebookAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: YOLOv8SageMakerStack/yolov8-notebookAccessRole/Resource
  yolov8notebookAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ecr:*
              - iam:PassRole
              - logs:*
              - sagemaker:*
            Effect: Allow
            Resource: "*"
          - Action: s3:ListAllMyBuckets
            Effect: Allow
            Resource: arn:aws:s3:::*
          - Action: s3:*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - yolov8
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - yolov8
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: yolov8-notebookAccessPolicy
      Roles:
        - Ref: yolov8notebookAccessRole
    Metadata:
      aws:cdk:path: YOLOv8SageMakerStack/yolov8-notebookAccessPolicy/Resource
  yolov8smnotebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.m5.4xlarge
      RoleArn:
        Fn::GetAtt:
          - yolov8notebookAccessRole
          - Arn
      AdditionalCodeRepositories:
        - "https://github.com/aws-samples/host-yolov8-on-sagemaker-endpoint"
      NotebookInstanceName: yolov8-sm-notebook
      VolumeSizeInGB: 5
    Metadata:
      aws:cdk:path: YOLOv8SageMakerStack/yolov8-sm-notebook
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1VRTW/CMAz9LdxDxsppR6imicsUlYkrSlOPeSUxShwQqvrflxJGttP7iPNiO5WsKrmY6UuYm66fH7GVw5a16UWy9kNYymEdTQ8s6k93ZxkUHdFci33XWax1gFEY6sCQtchyaOBEAZn87UpRowjLvQ4BOMjVBAJMJYfdyUx1O1ULFduUvI2ty10U1lBk+NDtEYpfvJRGBjUjuUfxRF43aoJ3zW+a4aKvQnk8J1qCN47BJ/5bkDu5qxWn/XxZcDwK1DaNRrmBG5a1ZJbm0wewugcvp1eJoSXqNy6wdiYtqY6ByTYQKHqTcx7835HydMYOvLitKX3SAd1B/L1Yk+twmncU6spf5J6W8nkhX2bfAXHuo2O0IJuMP6rqUT36AQAA
    Metadata:
      aws:cdk:path: YOLOv8SageMakerStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
